name: checar_coneccao_plugin
description: Plugin dart para verificar o status da conecção do dispositivo.
version: 1.1.2
homepage: https://github.com/pwlimaverde/checar_coneccao_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  connectivity: ^3.0.2
  
  flutter:
    sdk: flutter

  retorno_sucesso_ou_erro_package:
    git:
      url: https://github.com/pwlimaverde/retorno_sucesso_ou_erro_package.git

dev_dependencies:
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.vorfast.checar_coneccao_plugin
        pluginClass: ChecarConeccaoPlugin
      ios:
        pluginClass: ChecarConeccaoPlugin